<a href="https://colab.research.google.com/github/hugozub/MIAD/blob/main/Practica4_al263169.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
# Se crean dos matrices de 3x3 con número aleatorios del 1 al 10
matriz1 = np.random.randint(1, 11, size=(3, 3))
matriz2 = np.random.randint(1, 11, size=(3, 3))
print(f"Matriz 1:\n {matriz1}\n")
print(f"Matriz 1:\n {matriz2}")



Matriz 1:
 [[2 1 3]
 [1 6 3]
 [9 2 5]]

Matriz 1:
 [[2 6 7]
 [7 1 4]
 [7 5 4]]


In [ ]:
suma = matriz1 + matriz2
print(f"Suma matriz 1 + matriz 2: \n{suma}")

Suma matriz 1 + matriz 2: 
[[ 4  7 10]
 [ 8  7  7]
 [16  7  9]]


In [ ]:
resta = matriz1 - matriz2
print(f"Resta matriz 1 - matriz 2: \n{resta}")

resta matriz 1 - matriz 2: 
[[ 0 -5 -4]
 [-6  5 -1]
 [ 2 -3  1]]


In [ ]:
multiplicacion = matriz1 * 2
print(f"Multiplicación matriz 1 * matriz 2: \n{multiplicacion}")

Multiplicación matriz 1 * matriz 2: 
[[ 4  2  6]
 [ 2 12  6]
 [18  4 10]]


In [ ]:
producto_matricial = np.dot(matriz1, matriz2)
print(f"Producto matricial de matriz 1 y matriz 2: \n{multiplicacion}")

Producto matricial de matriz 1 y matriz 2: 
[[ 4  2  6]
 [ 2 12  6]
 [18  4 10]]
